### PR TITLE
Whitelist for SVG style attributes on data objects

### LINKED ISSUE #610: Whitelist style attributes on data objects
I'm having difficulty determining why this is, but I'm passing a data array (array of objects) to a bar chart, and I get this error:

> Warning: a `path` tag (owner: `Bar`) was passed a numeric string value for CSS property `TotalAcquired` (value: `38`) which will be treated as a unitless number in a future version of React.

When I try to debug, I find that the individual bars are being passed the values from my data array as styles. Those styles never end up getting applied to the resulting component, I'm guessing because they're not valid CSS, but React still complains about the unitless numbers. My implementation looks vaguely like this, (the dataTitle key ends up populating a custom tooltip):

```
const bars = [
  {
    TotalAcquired: "38",
    dataTitle: "Total Subscribers",
    date: "2017-02-01" 
  },
  {
    TotalAcquired: "47",
    dataTitle: "Total Subscribers",
    date: "2017-02-02" 
  },
  ...
]

<VictoryBar
  data={bars}
  x={datum => new Date(datum['date'])}
  y={datum => parseInt(datum['TotalAcquired'], 10)}
/>
```

### PR DESCRIPTION
**Pull request by kale-stew**
`sanitizeStyleProps` is running all user-input style data against a whitelist of valid SVG attributes and returning an object that contains only valid styles, dropping the rest.

Should resolve [Victory Issue #610](https://github.com/FormidableLabs/victory/issues/610)

### CODE REVIEW

**Comment by boygirl** [comment]
@kale-stew this is looking good. My only nitpick is that I'd like your sanitizeStyle method to live in the style util alongside the whitelist. Approved pending that change.

**Comment by kale-stew** [comment]
@boygirl done 👍

File: src/victory-util/style.js [hunk 1]
```diff
@@ -1,3 +1,30 @@
...
+  "xmlLang", "xmlSpace", "y1", "y2", "y"
+];
+
+/**
+ * Given an object with CSS/SVG style attributes, return a new object containing
+ * only keys that are also on our SVG style whitelist.
+ * @param {Object} data An object of user-input style attributes.
+ * @returns {Object} An object containing only valid style data.
+ */
+export const sanitizeStyleProps = function (data) {
```
Comment (boygirl) [inline src/victory-util/style.js]: I think this `export` is unnecessary, since you're exporting this method with your `export default` below

Comment (kylecesmat) [reply src/victory-util/style.js]: I just want to add a quick note here - I was pairing with Kylie and noticed that we cannot use named imports from default exports. I'm unfamiliar with the project semantics, but is this intentional?

ie, removing `export` here but then using the named `import { sanitizeStyleProps } from './style'` will cause `sanitizeStyleProps` to be undefined.

It looks the the way to avoid that is to import the entire module and path to the method like this https://github.com/FormidableLabs/victory-core/blob/73534d40536957e1a681f97ec776686371084895/src/victory-label/victory-label.js#L8

Not sure if this is a bug, or intentional but wanted to alert you, or @ryan-roemer to it.

**Comment by boygirl** [comment]
🎉 Looks good!
